name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1

      - name: Set up Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run UI Tests
        run: |
          mvn install
          mvn test -Dtest=UITests
          
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      - name: Run API Tests
        run: |
          mvn install
          mvn test -Dtest=APITests
