name: mainCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1  # Use v1 for more control
        with:
          chrome-version: stable

      - name: Install dependencies (Corrected)
        run: |
          sudo apt-get update
          sudo apt-get install -y libappindicator3-1 libasound2 libatk1.0-0 libcairo2 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libx11-6 libxext6 libxrender1 xvfb

      - name: Display Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Set Display (Important for GUI tests)
        uses: xvfb-action/xvfb@v2

      - name: Run UI Tests
        run: |
          mvn clean install -DskipTests=false  # Remove skipTests if you want all tests to run by default
          mvn test -Dtest=WebAutomation -Dsurefire.failIfNoSpecifiedTests=false

      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-reports
          path: target/surefire-reports/

  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run API Tests
        run: |
          mvn clean install -DskipTests=false # Remove skipTests if you want all tests to run by default
          mvn test -Dtest=APITests

      - name: Upload API Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: target/surefire-reports/