name: mainCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
        env:
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver

      - name: Set up Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run UI Tests
        run: |
          mvn install
          mvn test -Dtest=WebAutomation -Dsurefire.failIfNoSpecifiedTests=false
          
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run API Tests
        run: |
          mvn install
          mvn test -Dtest=APITests
