name: mainCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: latest

      - name: Display Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run UI Tests
        run: |
          mvn clean install -DskipTests
          mvn test -Dtest=WebAutomation -Dsurefire.failIfNoSpecifiedTests=false
        
      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-reports
          path: |
            target/surefire-reports/
            target/chromedriver.log
          
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run API Tests
        run: |
          mvn clean install -DskipTests
          mvn test -Dtest=APITests

      - name: Upload API Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: target/surefire-reports/